### ISSUE TITLE
添加注释会导致缩进改变

### ISSUE THREAD

**Issue by yl0412** [zhangfisher/json_comments_extension#1]
添加前是2空格为一个tab的缩进
<img width="946" alt="image" src="https://github.com/zhangfisher/json_comments_extension/assets/49944266/b7e4ff33-f3e4-4e55-861d-8123f3564e64">
添加后变成了4空格
<img width="988" alt="image" src="https://github.com/zhangfisher/json_comments_extension/assets/49944266/9ee142d6-3092-4933-ada2-ada89768a398">

一个不好的体验，期望能修复，很不错的项目，已start

**Comment by zhangfisher** [comment]
由于默认情况下，将注释内容保存到package.json下的<json-comments>键下，这样当保存注释时会重新格式化保存package.json，使用的是JSON.stringify(json,null,4)，所以会变成4空格。

是4缩进还是2缩进，不同人有不同的喜好。

我增加一个参数配置吧！

**Comment by zhangfisher** [comment]
如你所愿，升级`0.0.4`直接读`editor.tabSize`，不需要额外配置

**Comment by YL-python** [comment]
赞！
